#+TITLE: Buyer Beware [2017-08-04 Fri] 

** TL;DR
/somecrapo/

---------

Back in the day, when I aspired to become an artist/animator I embraced and
devoted myself to a process of questioning and ultimately disintegrating
critical aspects of my relationship with the popular culture. It remains to be
seen wether or not this was to my benefit but as a result I harbor some
seemingly unconventional ideas about how things fit together. It's not uncommon
that I might find myself being labeled a contrarian by some individual or
another, but those who know me understand I invest a significant amount of
calories into forming my own opinions. Part of the challenge in my endeavor to
take this step into a technical blog is to keep it technical. I'm an 'as above,
so below' kind of guy, my personal philosophy includes the concept that reality
is at its core a seemingly unintelligible contiguous multidimensional space,
that most of what we do as people is to impose mechanisms of arbitrary
categorization designed to help create an abstract mental model through which we
engage with this chaos. Critically, for myself, and for western society (at
least) I believe we've yet to fully embrace the responsibility or implications
of our ability to cleave this space, with our minds, into an understandable
environment. Without further belaboring of the point it is my opinion that the
motivation, creation, and distribution of software in this current industrial
landscape is woefully devoid of fundamental ethical or philosophical
consideration.

This is, like, a real problem. A problem in that, to my reckoning, there are few
if any _real_ values driving our so called technological 'innovation' other than
that where the excitement we as programmers, creators, and consumers experience
with novelty, overlaps with the profit motive. A lot of marketing terms and
buzzwords are employed to justify the creation and usefulness of some of our
more popular consumer technology offerings but not one of those employments is
immune to deep criticisms or are impervious to our darkest [ concerns ]. Each
press release brings a wave of concern for our collective privacy and safety
with regards to the proliferation of personal information and the implications
of increasing advancements in the algorithmic processing thereof. We have spent
decades and countless millions envisioning the A.I. driven apocalypse(in
fiction) to such resolution that some of todays most prolifiv thinkers are
publicly concerned that we are on a path towards it's manifestation(in reality),
yet we seem at a loss to prevent this from happening.  Made to read the great
distopic novels in High School but still, as a group of [oft quite young]
professionals, seem to be lacking the breadth of perspective to recognize that
we have one foot squarely in the domain of just that type of future, presently.

'Convenince' is a big thing in this regard. Indeed much of my criticism of
recent sociological trends stems from the observation of a divorce between the
superficial emotional attachments we have with the terms we use and the manifest
implications of the applications of these soft notions in the harder space of
'concrete' reality. Personal computing systems touted as being designed as
preconfigured integrations of hardware and software meant to unlock the
consumers creativity ultimately put them in a position of being held hostage
within a coorporate ecosystem, ultimately exposing to a sort of extortion and to
the homogenization of thier thought. 'Social media' platforms designed to
connect us personally manifest to alienate and depress the individual. To spiral
our conception of living into an outer space of self promotion, of consumption,
exess, self love, and indadequacy. A few years ago the obsessive buzzword in
Silicon Valley was 'disruption'. Where that term is a distinctly amoral
descriptor of an affect we see a rise of technologies that threaten the
livelyghood of individuals in that arena of lifestyle that is the ovelap of our
economic and phsycological lives (rise of the automotron).

I get it, myself half subscribed to the popular story we tell ourselves about
the ever forward progress of civilization. It's unavoidable that things will
change and transitions are innately accompanied by feelings of discomfort as our
perceptions readjust. Can't make an omlette...etc. But are we in fact master
chefs carefully selecting and measuring our ingredients, adeptly transmuting
them with tools and technique through an alchemical process to create the dish
we forecast in our minds? Or are we more like unsupervised children tossing
groceries against the wall, playing with a stove that could seriously burn us?
Just cuz you break the eggs doesn't mean the omelet is going to come together.
Especially if its difficult to create the mental image of the Omlette in the
first place. There is a large degree of the current human activity that happens
as a result of compulsion as opposed to deliberation.

We loose something when delegate responsibility. For instance as I have (or have
accepted to) offset the responsibility of food production to the Farmer, at the
time of this writing I have only a loose conception of how long it takes an
apple to grow from flower to fruit, let alone how long from seed to fruit.
Indeed I've spent 3 decades without knowing how the apple forms form the
flower(hint: the secrets in that star shaped structure on the bottom). Its a
fact that men and women live full and 'complete' lives without any significant
relationshiop to the natural mechanisms which aid the sustenance of that
existence. With regards to mere survival, fine, so long as I'm close to
civilization, but I'm sure I would have a hard time in the wilderness if
suddenly lost there tomorrow. There is a deeper issue though, and it's one of
context; for if I don't have a relationship with and understanding of the
natural process by which foodstuffs come into being than I lack some
understanding about myself and my place in the ecosystem, the world, and the
cosmos.

We are hard pursuing a path towards offsetting our material responsibilities on
machines as much as we can. This has been part of the vision for sometime, a
future where automatons are handling all of our mundane business leaving us to
lives of liesure, or to pursue humanities true calling. However, the society
that we are witnessing develop (and are ourselves developing) is not out of the
pages of a Popular Mechanics magazine from the 30s; that vision was wallowed to
be a pure fantasy, unattached from its historical reality let alone the laws of
physics. What we have now is something different that is moored to the rules of
our time based reality(whatever those are) and can't be formed outside of the
context of the sedentary history of our modes of thought, our limited
creativity, and selective application of the least common denominator of our
consensus ethical set. There is and perhaps always has been a space between the
buyer and the seller for dishonesty, most deceifully on the part of the seller.
Today we are messing with forces which, at the least, have the power to
fundamentally alter our perception of reality and, at worse, to destroy us in
that horrible way that only some premenisced nightmare come to life can.

Like many people (I imagine most) I started my relationship with computing in a
state of total infatuation. For maybe decades what drove my further adventures
deeper and deeper into the jungles of algorithmic data transformation was mostly
the novelty of it all, and being inspired to make video games. Insofar as I can
love a thing inanimate and conceptual I love computer programming. I put it in
the same supercategory as the visual arts or music, with all thos same cultural
implications. We tell ourselves that technology solves problems without
recognizing its fundamentally hydra like nature; for every solution applied
multiple other issues spring up. This is a rule. Nay, the technology isn't for
problem solving but for perspective framing, for molding facets onto our
personal and collective models of what-the-fuck-is-going-on-here? On the long
timeline, we as a species of animals will have to embrace and guard our natural
mandate to deliberately define our perspective on reality and the terms under
which we will and will refuse to address it under. As far as I can see our
scientific and technical culture(to say the least) doesn't really have the
ability to say 'we can do this, but we choose not to'.

This is a '.github.io' namespace, what follows will be focused on that which is
appropriate to commit under the theme of version control. Namely software. I've
only a few truly interesting visions with regards to computer programming and
I'm hoping to document some of the process of their development here.
