#+TITLE: Buyer Beware [2017-08-04 Fri] 

Back in the day, when I aspired to become an artist/animator, I embraced and
devoted myself to a process of questioning and ultimately disintegrating
critical aspects of my relationship with the popular culture. It remains to be
seen whether or not this was to my benefit but, as a result, I harbor some
seemingly unconventional ideas about how things in general fit together. It's
not uncommon that I find myself being labeled a contrarian by some individual or
another, but those who know me understand I invest a significant amount of
calories in forming my own opinions.

My personal philosophy includes the concept that reality is at its core a
seemingly unintelligible contiguous multidimensional space-- that most of human
activity revolves around the imposition and upholding of mechanisms of arbitrary
categorization intended to help create abstract models through which we can hope
to engage with this chaos. Critically, for myself, and for western society (at
least) I believe we've yet to fully embrace the responsibility or implications
of our ability to cleave this space, with our minds, into an understandable
environment. We have created myriad tools to achieve this effect some of the
most crucial include spoken language, written language, and telecommunications.
Some of the world's most prominent thinkers and scientists would agree with me
when I say that with the passage of time the efficiencies with which our
technology can impact our psychic space continues to increase. Without further
belaboring the point it is my opinion that the motivation, creation, and
distribution of software in this current industrial landscape is woefully devoid
of fundamental ethical or philosophical consideration.

This is, a real problem. To my reckoning, there are few if any _real_ values
driving our so-called technological 'innovation' other than those found in the
space where the excitement we as programmers, creators, and consumers experience
novelty overlaps with the profit motive. A lot of marketing terms and buzzwords
are employed to justify the creation and usefulness of some of our more popular
consumer technology offerings, but not one of those deployments is immune to
deep criticisms or are impervious to our darkest misgivings. Each new product or
feature release brings a wave of concern for our collective privacy and safety
with regards to the proliferation of personal information and the implications
of increasing advancements in the algorithmic processing thereof. We have spent
decades and countless millions developing and consuming visions of the A.I.
driven apocalypse(in fiction) to such a resolution that some of today’s most
prolific thinkers are publicly concerned that we are on a path towards its
manifestation(in reality), yet we seem at a loss to prevent it from happening.
We’re made to read the great dystopian novels in High School but still, as a
group of professionals, we seem to lack the breadth of perspective to recognize
that we have one foot squarely in the domain of just that type of future,
presently.

The Human Being is, for lack of better description, an emotional computation
machine. There is an aspect which sits behind consciousness which figures on
maddening volumes of data in incomprehensibly small spans of time and returns
information to our awareness in the form of gut feeling, or dream, or
instantaneous reaction to a threat not yet consciously recognized. A lot of the
knowledge we individually posses about the world comes to us this way; through
long form trial and error the subconscious discovers patterns and returns them
to our awareness in the form of subtle notions. (How *did* you figure out to
blow on the cartridge and half insert it into your NES to get the game to work?)
It is only later on in the process of thought where an attempt can be made to
package these subtle notions and label them with a term. Spoken/Written
language, then, being a system of call-by-reference to the lower realm where
concepts are actually interacting. Much like in our computer languages the
variable name and the data it maps to are somewhat arbitrary. The relationship
between the *name* of the reference and the meaning of the data it represents
being quite loose and really only supported by the psychic consensus of the
authorities (if any) of the codebase. My point being that in source code, if you
read a variable name you might get some notion about the previous developers
intention for that particular reference, but you might be wrong, or off
slightly. The same applies to spoken language, we tend to have an assumption (or
an ambivalence to the idea) that when I invoke the words ‘red apple’ that they
manifest a similar image in your mind and my mind. I posit this is not
necessarily the case and further sometimes, even when it is, both of our mental
images lack resolution.

'Convenience' is a big thing in this regard. Indeed, much of my criticism of
recent sociological trends stems from the observation of a divorce between the
superficial emotional attachments we have with the terms we use, and the
manifest implications of applying these soft notions in the harder space of
'concrete' reality. Personal computing systems touted as being designed as
preconfigured integrations of hardware and software-- meant to unlock the
consumer’s creativity-- ultimately put them in a position of being held hostage
within a corporate ecosystem, exposing them to a sort of extortion and
homogenization of their thought. Social media platforms promoted to connect us
personally, in actuality manifest to alienate and depress the individual. To
spiral our concept of living into an outer space of self promotion, of
consumption, excess, narcissism, and inadequacy. A few years ago the obsessive
buzzword in Silicon Valley was 'disruption'. Where that term is a distinctly
amoral descriptor of an effect we see a rise of technologies that threaten the
livelihood of individuals. People harnessing themselves to be directed by
algorithm in exchange for cash. It’s only face, an arbitrary star rating system
which holds real fates in the balance.

I get it. I, myself, half subscribed to the popular story we tell ourselves
about the ever forward progress of civilization. It's unavoidable that things
will change and that transitions are innately accompanied by feelings of
discomfort as our perceptions readjust. Can't make an omelette...etc. But are we
in fact master chefs, carefully selecting and measuring our ingredients, adeptly
transmuting them with tools and technique through an alchemical process to
create the dish we forecast in our minds? Or, are we unsupervised children
tossing groceries against the wall, playing with a stove that could seriously
burn us? Just cuz you break the eggs doesn't mean the omelet is going to come
together. Especially if it’s difficult to create the mental image of the
Omelette in the first place. There is a large degree of the current human
activity, especially as it pertains to the creation of technology, that happens
as a result of compulsion as opposed to deliberation.

We lose something when we delegate responsibility. For instance as I have (or
have accepted to) offset the responsibility of food production to the farmer, at
the time of this writing I have only a loose conception of how long it takes an
apple to grow from flower to fruit-- let alone how long from seed to fruit.
Indeed I've spent three decades without knowing how the apple forms form the
flower(hint: the secret is in that star shaped structure on the bottom). It’s a
fact that modern men and women live full and 'complete' lives without any
significant relationship to the natural mechanisms which aid in sustaining of
that Existence. Only a real problem if civilization collapses and the Whole
Foods down the block decides to close (looking less likely recently). There is a
deeper issue though, and it's one of context; for if I don't have a relationship
with and understanding of the natural process by which foodstuffs come into
being than I lack some understanding about myself and my place in the ecosystem,
the world, and the Cosmos. Perhaps some information critical to helping me/us
healthily get situated within this grand clockwork.

We are hard pursuing a path towards offsetting our material responsibilities on
machines as much as we can. This has been part of a universal vision for
sometime-- a future where automatons handle our mundane business leaving us to
enjoy lives of leisure, or (more optimistically) pursue humanity’s true calling.
However, the society that we are witnessing (and are ourselves) developing is
not out of the pages of a Popular Mechanics magazine from the 30s; that vision
wallowed in a pure fantasy, unattached from its historical reality let alone the
laws of physics, or the evolving guidelines of economics. What we have now is
something different that is moored to the rules of our time based
reality(whatever those are) and can't be formed outside of the context of the
sedimentary history of our modes of thought, our limited creativity, and
selective application of the least common denominator of our consensus ethical
set. There is and perhaps always has been a space between the buyer and the
seller for dishonesty, and historically most deceitfully on the part of the
seller. Today we are messing with forces which, at the least, have the power to
fundamentally alter our perception of reality and, at worse, to destroy us in
only the way a a horrible a nightmarish premonition come to life can.

Like many people (I imagine most) I started my relationship with computing in a
state of total infatuation. For maybe decades what drove my further adventures
deeper and deeper into the jungles of algorithmic data transformation was mostly
the novelty of it all, and being inspired to make video games. Insofar as I can
love a thing inanimate and conceptual I love computer programming. I put it in
the same super-category as the visual arts or music. We tell ourselves that
technology solves problems without recognizing its fundamentally hydra like
nature; for every solution applied, a multitude of other issues spring up. This
is a rule. Nay, Technology isn't for problem solving but for perspective
framing-- for molding facets onto our personal and collective models of
‘what-the-fuck-is-going-on-here?’ On the long timeline, we as a species will
have to embrace and guard our natural mandate to deliberately define our
perspective on reality and the terms under which we will and refuse to address
it. As far as I can see our scientific and technical culture(to say the least)
don’t really have the ability to say '*/we can do this, but we choose not to/*'.

This is a '.github.io' namespace, what follows will be focused on that which is
appropriate to commit under the theme of version control. Namely software.
