#+TITLE: Untitled [08-30-2016]  
Mutherfucking redo, right?

Today I invented a new word, pretaliate. I suspect I'll spend some time into the
future examining what meaning, embedded in this minor rehash of a fairly popular
term, tickles me so. I'm a little enebreated right now so the typos are a
flowin'...I'm supposed to write something here, but I'm honestly unsure of what.
I'm trying generally to avoid writting a diary entry. It is weird, however, that
when I assert myself, seemingly, I create conflict. That my particular
conyribution to this space is more disruptive than constructiuve.

I talk alot of shit about it and have been accussed by the one who got closest
of an absemce of passion. Whether she meant fundamentally or just as
encorporated into my actions is somewhat beside the point. Another one, who I've
called a modern friend of mine, but have recently come into conflict with, tells
me I need to get laid. Beneath the surface of what seems like a calm ocean is a
raging undertow of emotion. After nearly 4 decades I still feel the unsatisfied
requirement to satisfy my creative urge. The depth of which has to this point
intimidated me to the effect of preventing any meaningfull forward progress.

It alsways seems to me as too extreme, the prospect of the stance I would have
to assume to even attempt a resolution in thes terms. I'm not entirely sure I'm
not crazy and I would need to seriously entertain the manifestation of those
extreme aspects of my personality into material space to finally be certain and
resolved either way. For all I know I came this close to being arrested the
otherday for not standing off the yellow safety strip on the Bart platform the
other day. But regardless I'm caught between the zones of predictable confort
that I've learned how to develop and maintain and the wire. The tightrope that
was set up for me and me alone to step across this chasm of uncertainty.

As I take measure of the world I've known for some time but have until recently
accepted the breadth of it's absurdity; the notion that this world can support
this much possibility that Donald Trump could become president, "Black Lives
Matter", 4 gen feminism, transgenderism, etc. In the face of this, I've to ask
myself how crazy really are any of the actions I would intend to take? Probably
not that crazy...likely, as with a child convincing himself that they don't like
brussels sprouts inadvertently by cause of being exposed to Beaver Clevers
aversion to brussels sprouts, I had a falitious idea in the past about the level
of daunt involved in pursuing any of my inspirations and still have yet to do
the requisite work to determine the realistic weight of said ideas truthyness.

In that hypothesis is folded in the direness of my situation and perhaps the
direness of the grander social situation as a whole. That my days and moments be
wasted if I'm not ernestly acting to challenge these fundamental assumption and
push the envelope of my personal creativity in this material space. The idea
that it's not good enough to come to an workable understanding of the
established arbitrary and superficial rules of our western society but that I
personally have been given a mandate to work to help inform the next iteration
of these superfical rules, that the next permutation could incoorporate that
much more of an iota of the profound and mysterious truth of the natural
dynamic.

Pretaliation means anticipating the impending offense for which there will be a
requisite response and delivering that response prior to the offense.

More concretely, from this point, I'm to replace the synthetic elation provided
by cigarettes, alchol, weed, binge netflixing, and longing for specifc as well
as general companionship with earnest and purposeful pursuit of manifesting my
nuttiest creative visions. Noteably the Nekuronokuse, project codenamed
Ouroboros, and the general exposition and promotion of my social and
technological critism and philosophy.

I am not resolved on that point. Indeed it is the purpose of this exercise to
furthr stimulate the mind into recognizing that there is nothing left in this
world for me but these not quite well formed points. That despite the expansion
historical expansion of my perception of the details of this environment and the
relative expansion of my modes of communication, my relative mastery of crafts,
that the preperation that I had always felt I was under has lent itself to this
moment where I must actualize my theoretical knowledge of the world in general
terms.

This needs to be extreme, it was written that I should pursue those thigs which
frighten me. This should be total war. Against myself primarily, but also
against the world of people.

Guerra Todos

Guerra Todos

Guerra Todos.
